version: '3.8' # Asegúrate de usar una versión que soporte deploy

services:
  app:
    build: .   # <-- ¡Cambia ./src por un punto!
    deploy:
      replicas: 3


  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    # ESCALAMIENTO VERTICAL: Asignación de recursos específicos
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Límite máximo: Nivel de CPU (medio núcleo)
          memory: 512M     # Límite máximo: 512 Megabytes de RAM
        reservations:
          cpus: '0.25'     # Recursos garantizados
          memory: 256M
