services:
  web:  # <--- CAMBIAMOS 'app' POR 'web'
    build: .
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web # <--- CAMBIAMOS 'app' POR 'web'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
